# Site settings
title:          "Blog C/Embedded/Hardware User Group - Łódź"
description:    "Blog dla profesjonalistów i amatorów zainteresowanych wszelkimi aspektami systemów wbudowanych"
url:            "https://cehug-lodz.github.io"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Lodz C/Embedded/Hardware User Group
  url:          https://cehug-lodz.github.io

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
